bxcodec/faker

- credit_card.go
- faker.go
- faker_test.go
- glide.lock
Based on #1 
* added email generator. Still using random text and random domain
* added Credit Card Generator . Just a Random Number, with predefined CC (VISA,MASTERCARD, AMEX, DISCOVER)
* added IP Addres Generator (IPV4 & IPV6) 
* added LATITUDE and LONGITUDE generator (float32 & float64)
Example of use : 
```go
type SomeStruct struct {
Latitude         float32 `faker:"lat"`
Longitude        float32 `faker:"long"`
String           string
CreditCardType   string `faker:"cc_type"`
CreditCardNumber string `faker:"cc_number"`
Email            string `faker:"email"`
IPV4             string `faker:"ipv4"`
IPV6             string `faker:"ipv6"`
}
func SampleFunc(){
var a SomeStruct
err := FakeData(&a)
if err == nil {
fmt.Printf("%+v", a)
}
}
```
> add userdefined data

- address.go
- faker.go
- internet.go
- payment.go
* Using custom sources results in the RNG becoming non-thread safe. Using the default source guarantees that multiple threads are able to generate data using faker safely as per the Go docs (https://golang.org/pkg/math/rand/).
> Thread safety by using the default source for the RNG

- faker.go
fixes if a struct contains a named/assigned type (#25)
> fix panic on named types

- datetime.go
- datetime_test.go
Previously using the `day_of_week` tag, as in
```
DayString string `faker:"day_of_week"`
```
would always return `Sunday`. Tracked this down to the fact that the code needs to use constants from the reference time `"Mon Jan 2 15:04:05 MST 2006"` as described https://gobyexample.com/time-formatting-parsing. So the correct value to use is `Monday`.
Also included in this PR one way to test that we are not always getting the same value returned from the function.
> Bugfix: DayOfWeek now returns random day

- README.md
- faker.go
- faker_test.go
- person.go
- person_test.go
I need to generate a random first name of either gender, so added support for that here. From a user perspective, if they choose to define a struct with either TitleMale or TitleFemale, they should also use FirstNameMale or FirstNameFemale.
But if they only need a FirstName and a LastName, this makes it possible to generate Persons of random gender.
> adds support for FirstName of either male or female gender

- faker.go
- faker_test.go
Hello. Thank you for good library. But I don't see ability to skip some fields for faking data. This PR should be fix it.
> feat: Add skipping field tag

- faker.go
- faker_test.go
Hello. This pull request added ability to add new tag in faker with custom providers. Existing tag cannot be rewritten
> Add extending faker by custom providers

- .changes
- README.md
- address.go
- datetime.go
- faker.go
- faker_test.go
- internet.go
- internet_test.go
- lorem.go
- lorem_test.go
- payment.go
- payment_test.go
- person.go
- phone.go
- price.go
- price_test.go
- support/slice/helpers.go
Price added | Comments added | Code Documented and styled according to GoLang Wiki: https://github.com/golang/go/wiki/CodeReviewComments 
**1. price.go**
- Prices are often used with Currency Codes and hence, one can use the price tags to have mock prices
**2. helpers.go**
- SliceIntToString -> IntToString
**3. faker.go**
- tags string name changed 
- DAY_OF_MONTH -> DayOfMonthTag
- TIME_PERIOD -> TimePeriodTag
**4. internet.go**
- https(secure) urlFormats added
- Url -> Url
- Ipv4 -> Ipv4
- Ipv6 -> Ipv6
**5. lorem.go**
- Sentences -> Paragraph
- Sentence now, directly ends with a full stop, not a space followed by full stop.
- A randomized Paragraph is generated having lines <= 10
**6. person.go**
- New Titles added
- Male names starting with 'Y' and Female names starting with 'X' are …
> feat: Added price (amount and currency) | Code commented and styled

- .gitignore
- README.md
- faker.go
- faker_test.go
- uuid.go
- uuid_test.go
Added Identifier for faker.
Usage:
`faker:"uuid_digit"` xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
`faker:"uuid_hyphenated"` xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
close #39
> feat: UUID Generator

- faker.go
- faker_test.go
There was a panic while faker tries to generate data for custom scalar type pointers
> fix: fake data generation for custom scalar type pointers

- README.md
- address.go
- datetime.go
- datetime_test.go
- faker.go
- faker_test.go
- internet.go
- internet_test.go
- lorem.go
- lorem_test.go
- payment.go
- payment_test.go
- person.go
- person_test.go
- phone.go
- phone_test.go
- price.go
- price_test.go
- uuid.go
- uuid_test.go
Proposed changes:
Now we can easily add our own custom faker-generator provider.
Example: 
```go
type Gondoruwo struct {
Name       string
Locatadata int
}
func CustomGenerator() {
faker.AddProvider("customIdFaker", func(v reflect.Value) (interface{}, error) {
return int64(43), nil
})
faker.AddProvider("danger", func(v reflect.Value) (interface{}, error) {
return "danger-ranger", nil
})
faker.AddProvider("gondoruwo", func(v reflect.Value) (interface{}, error) {
obj := Gondoruwo{
Name:       "Power",
Locatadata: 324,
}
return obj, nil
})
}
type Sample struct {
ID                 int64     `faker:"customIdFaker"`
Gondoruwo          Gondoruwo `faker:"gondoruwo"`
Danger             string    `faker:"danger"`
}
```
Results:
```
{ID:43 Gondoruwo:{Name:Power Locatadata:324} Danger:danger-ranger} …
```
> fix: custom provider generator

- README.md
Here's a small PR to improve the english in the second part of the README. I took the freedom to also rephrase certain sentences in order to make them clearer.
PS: really love that small library ;-)
> Correct and rephrase the README

- payment.go
It is not clear to me why they have been duplicated in the first case, so if I have missed something obvious please accept my apologies!
> chore: remove duplicate creditCard definitions.

- .gitignore
- faker.go
- faker_test.go
`SetNilIfLenIsZero` called method is added for the setting nil option.
Ref: #58
> Optionally insert nils instead of empty slices and maps

- .gitignore
- README.md
- faker.go
- faker_test.go
String len, number boundaries and array and map size have become configurable. In reference task, it was asked as a tag but I think, adding two new unnecessary field will be pointless for length setting instead making configuration will be more convenient. So It has become configurable with this PR...
fix #49
> feat(faker): length Support

- faker.go
- faker_test.go
Sometimes I want to keep the original value of a struct property. Therefore I added a tag `keep` which allows me to keep the initially set value. It still sets the value if it is the zero value of a field.
> Add support for keeping struct property values

- faker.go
- faker_test.go
> feat(custom-faker): add map support to custom fakers 

- README.md
- SingleFakeData.md
- WithStructTag.md
- address.go
- datetime.go
- faker.go
- faker_test.go
- internet.go
- lorem.go
- lorem_test.go
- payment.go
- person.go
- phone.go
- price.go
- support/slice/helpers.go
- uuid.go
Refer to issue #76 
- Added a `unique` tag to generate unique data.
- Call `ResetUnique()` after generating a dataset to forget all already generated values
- Added tests for the new feature
- Added unique support for `Lorem` generator as a proposal for the single fake data functions. My implementation is redundant. **Any feedback would be appreciated before implementing it to the other single fake data functions.**
- Call `SetGenerateUniqueValues(true)` to enable unique data generation on single fake data functions
- Call `SetGenerateUniqueValues(false)` to disable it
- Call `ResetUnique()` to forget all already generated values
This change shouldn't break backwards compatibility.
TODO:
> feat(faker): unique data generation

- faker.go
- Extend ErrTagUnsupported to include the bad tag
> Extend Error Messages

- faker.go
- faker_test.go
The updated faker test will product the following without the convert update for slices.
```
panic: reflect.Set: value of type int32 is not assignable to type faker.SomeInt32 [recovered]
panic: reflect.Set: value of type int32 is not assignable to type faker.SomeInt32
goroutine 34 [running]:
testing.tRunner.func1.1(0x1162b20, 0xc00017f960)
/usr/local/Cellar/go/1.14/libexec/src/testing/testing.go:941 +0x3d0
testing.tRunner.func1(0xc000166240)
/usr/local/Cellar/go/1.14/libexec/src/testing/testing.go:944 +0x3f9
panic(0x1162b20, 0xc00017f960)
/usr/local/Cellar/go/1.14/libexec/src/runtime/panic.go:967 +0x15d
reflect.Value.assignTo(0x11622e0, 0xc00018402c, 0x85, 0x11a5a9a, 0xb, 0x1162220, 0x0, 0x33, 0xc000186000, 0x17)
/usr/local/Cellar/go/1.14/libexec/src/reflect/value.go:2403 +0x426 …
```
> fix: special slice types cause panic when reflectively generating values

- faker.go
Current code accepts 0 as a valid number for `SetRandomMapAndSliceSize` then panics on the Intn call with `panic: invalid argument to Intn`
> fix: 0 not valid for random size

- README.md
- example_with_tags_lang_test.go
- faker.go
- faker_test.go
- internet.go
I thought it would be nice to check string encoding, if you have possibility to generate strings in  different languages.
fix #94
> new lang tag, chinese + russian lang generators

- README.md
- example_custom_faker_test.go
- faker.go
- faker_test.go
Before, even if using `AddProvider()` some custom types would not work, as there was no check for `mapperTag[tag]` function before calling `userDefinedArray()`.   
^ it would fail with `Tag unsupported: ....` even if provided with a tag!
Since `AddProvider()` can provide the ability to instantiate/manipulate the type, it would be great if when using `AddProvider()` the user could provide a tag that would work even for some custom types.   
If you comment out the changes I made to `faker.go` and run the tests `go test ./...` you will see the failure, even though `AddProvider()` was called to add the desired tag.
Fixes issue https://github.com/bxcodec/faker/issues/101
> Allow AddProvider to still work with some custom types

- example_custom_faker_test.go
- faker.go
- faker_test.go
`go fmt` + fixed error:
```
$ cat > /tmp/1.go <<EOF
package main
import "github.com/bxcodec/faker"
type array [16]byte
func main() {
var a array
faker.FakeData(&a)
}
EOF
$ go run /tmp/1.go
panic: reflect.MakeSlice of non-slice type
goroutine 1 [running]:
reflect.MakeSlice(0x53d860, 0x4eed00, 0xd, 0xd, 0x0, 0x0, 0x0)
/home/xaionaro/.gimme/versions/go1.13.linux.amd64/src/reflect/value.go:2256 +0x1d8
github.com/bxcodec/faker.getValue(0x4eed00, 0xc0000163a0, 0x191, 0x4eed01, 0x4eed00, 0xc0000163a0, 0x20300000000000)
/home/xaionaro/go/src/github.com/bxcodec/faker/faker.go:444 +0xca0
github.com/bxcodec/faker.getValue(0x4dea40, 0xc000016380, 0xc00000e240, 0xc00000e220, 0x40c556, 0xc00000e1e0, 0xc00000e1c0)
/home/xaionaro/go/src/github.com/bxcodec/faker/faker.go:355 +0x169e …
```
> bugfix(faker): don't panic on typed array

- README.md
- example_custom_faker_test.go
- example_with_tags_test.go
- faker.go
- faker_test.go
- This adds support for a `faker:"oneof: val1 :val2 :val3"`
- Currently only `string` and `int` is suppported
- I would be happy to add support for more types at a later time
- This looks like it might fix (or at least partially fix) https://github.com/bxcodec/faker/issues/82
> feat: Implement oneof tag

- README.md
- example_with_tags_test.go
- faker.go
- faker_test.go
- tag_argument_extractor.go
- tag_argument_extractor_test.go
- add support for float32
- ensure support for both float32 and float64
- lint fixes
- add tests for float64 & add test for nil pointer""
fix #82
> oneof float support

- README.md
- example_with_tags_slicelength_test.go
- faker.go
- faker_test.go
Adds the possibility to set a specific slice length for all types of slices.
Tag: `slice_len=$d` with $d a number >= 0
Fixes #92
> feat: Adds Slice length tag

- example_with_tags_test.go
- faker.go
- faker_test.go
- internet.go
- internet_test.go
Added jwt-token support in case someone wants to write tests on their 'Passport service' or something like it
> added fake jwt-token support

- faker.go
- faker_test.go
- go.mod
This method removes existing customization added with AddProvider.
This can be useful if you need to reset your customization and add
a new one with the same name.
> feat: Add RemoveProvider public method

- faker.go
- faker_test.go
- go.mod
This PR adds a flag that tells faker to ignore the population of interface{} types.
This is useful when populating complex structures for Marshal testing, where you don't have the control or ability to use a non-interface{}. This makes testing complex structure marshaling a LOT simpler, since otherwise you would have to faker every element in the structure above and beside an interface{}.
The default behavior is to not ignore interface{}, so no behavior changes should be seen.
A test has been added.
Thanks!
> feat: Add ability to ignore interface{} population with SetIgnoreInterface()

- address.go
- datetime.go
- faker.go
- faker_test.go
- internet.go
- lorem.go
- payment.go
- person.go
- phone.go
- price.go
- random_source.go
- random_source_test.go
- tag_argument_extractor.go
- uuid.go
This PR adds the ability to set custom random sources at the package level.
* fixes #138 
Signed-off-by: Frederic BIDON <fredbi@yahoo.com>
> added random source customization

- example_with_tags_lang_test.go
- faker.go
- faker_test.go
It corresponds to Japanese hiragana and katakana.
Kanji is not supported due to its wide range.
> Support for Japanese hiragana and katakana

- support/slice/helpers.go
https://github.com/bxcodec/faker/blob/7460bf3a84de3afbfe7297c488c711d29f09c5d2/support/slice/helpers.go?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L7-L16
we don't need to make a map to check a slice contain a string, just do it in `for range`
> check slice.Contains in `for range` block

- faker.go
- faker_test.go
The documentation on randomInt was confusing and said it could accept a third parameter. In reality, it threw an error if you gave a third parameter. This change makes that third parameter work and rewords the documentation.
("Number of digits" suggested that it was about 1-digit numbers like 7 versus 3-digit numbers like 152. It's about the minimum integer and maximum integer, though, so I changed the docs and variable names to reflect that.)
> fix docs for randomInt and update code to support documented third argument

- faker.go
- faker_test.go
wish to add a feature that can set minimum random size for slice and map
> feat: add min max size for random slice map And allowing one element for Oneof

- example_with_tags_lang_test.go
- faker.go
- faker_test.go
Support for Korean Hangul language
Usage:
```go
StringKOR string `faker:"lang=kor"`
```
Output:
```
StringKOR:텻밚쨋큊몉
```
> Support for Korean Hangul

- example_with_tags_lang_test.go
- faker.go
- faker_test.go
Support for Emoticons
But still using `lang` tag
Usage:
```go
StringEMJ string `faker:"lang=emj"`
```
Output:
```
StringEMJ:🐅😄🕢🍪🐡
```
> Support for Emoticons

- example_with_tags_lenbounds_test.go
- faker.go
- faker_test.go
Hey, @bxcodec.
I have no idea why float32 and float64 isn't support boundaries tags. This is why I made this PR.
What is reason of that this isn't made before? I want to discuss it cause I can don't realize some fatal reasons of this. Please, take a look.
What made by me:
* added ability to set boundaries for float32 and float64 types;
* rename old methods which supports only integers to more explicit;
* update tests;
* delete test which checks float to unsupported struct to boundaries.
> Float boundaries

- example_with_tags_test.go
- faker.go
- faker_test.go
Thank you for the good library.
Now I need to set `oneof` for a pointer type.
(It cannot be non-ptr because it is necessary to distinguish between nil and 0)
I think this feature is in demand by users other than me, so I will create a PR.
In this PR, we becomes to be able to use other tags other than `oneof` at the same time on pointer types.
> `oneof` support for some pointer types.

- lorem.go
- phone.go
```
phone.go:70:47: SA4030: (*math/rand.Rand).Intn(n) generates a random value 0 <= x < n; that is, the generated values don't include n; rand.Intn(1) therefore always returns 0 (staticcheck)
return fmt.Sprintf("(%s) %s", boxDigitsStart[rand.Intn(1)], out)
^
phone.go:94:45: SA4030: (*math/rand.Rand).Intn(n) generates a random value 0 <= x < n; that is, the generated values don't include n; rand.Intn(1) therefore always returns 0 (staticcheck)
return fmt.Sprintf("+%s%s", boxDigitsStart[rand.Intn(1)], strings.Join(slice.IntToString(ints), ""))
^
```
> fix: Always get the same value where you want to get it at random.
